export const data = [
  "I'm baby sartorial succulents semiotics, praxis selfies wayfarers mukbang cray jianbing actually forage gorpcore you probably haven't heard of them. Photo booth vinyl paleo, mixtape cloud bread pabst mlkshk squid af blackbird spyplane solarpunk. Gochujang sriracha copper mug, plaid kombucha roof party locavore asymmetrical butcher vice bitters organic. Raclette forage DIY fixie polaroid, locavore sustainable gentrify. Viral tumblr vape jianbing neutral milk hotel cold-pressed polaroid put a bird on it slow-carb",

  "Adaptogen intelligentsia single-origin coffee cold-pressed pour-over letterpress dreamcatcher. Portland distillery sartorial iceland banjo blog. Echo park bruh try-hard, fixie marxism iceland hashtag twee solarpunk semiotics succulents meh glossier. Tacos selfies snackwave, single-origin coffee roof party ennui chartreuse hexagon shabby chic man braid cardigan 3 wolf moon keytar vape. Fit small batch glossier, aesthetic polaroid letterpress cray try-hard.",

  "Migas flannel drinking vinegar XOXO, squid fixie keffiyeh hoodie cronut. Lomo austin godard, vegan heirloom fashion axe street art gatekeep neutral milk hotel YOLO hexagon bodega boys. Mlkshk godard activated charcoal lo-fi. Cronut ramps pickled poke adaptogen you probably haven't heard of them organic ascot microdosing semiotics tilde air plant jianbing normcore. Viral mixtape beard hell of tumblr lo-fi. Snackwave man braid la croix, yes plz brunch lomo pabst stumptown mukbang. Affogato leggings umami VHS live-edge",

  "Unicorn bitters woke DSA humblebrag cliche fixie. Blog vice Brooklyn fixie pug letterpress. DSA tbh bespoke YOLO, organic biodiesel marxism four loko quinoa skateboard poke mixtape. Lomo hashtag keytar pop-up hell of fixie VHS af raclette gentrify gochujang master cleanse schlitz iPhone art party.",

  "Four dollar toast big mood wolf tumeric. Humblebrag copper mug squid pinterest fixie grailed. Man bun sriracha keytar affogato, taiyaki pitchfork 90's single-origin coffee fit slow-carb synth everyday carry poutine tumblr XOXO. Hell of craft beer DSA, palo santo raw denim schlitz lo-fi. Bruh kickstarter raclette, ugh gastropub mixtape hot chicken pork belly vegan vice. Waistcoat roof party pickled poutine cray, praxis craft beer microdosing paleo chicharrones normcore tousled ennui hot chicken. Heirloom yuccie chambray tumeric gatekeep gentrify.",

  "Vegan same freegan health goth chia gatekeep authentic austin. Cray before they sold out fam literally hell of activated charcoal, four dollar toast cold-pressed bodega boys keytar church-key cornhole locavore adaptogen vice. Flannel sus williamsburg blackbird spyplane sriracha. Asymmetrical sriracha affogato, cold-pressed adaptogen messenger bag pabst knausgaard man braid pitchfork four dollar toast. Franzen godard salvia meh wolf lyft.",

  "Godard pork belly messenger bag gluten-free. Ramps distillery normcore gluten-free succulents umami blackbird spyplane trust fund locavore beard kitsch wayfarers kogi. Yuccie four dollar toast paleo, marxism kale chips quinoa messenger bag fit blog biodiesel vegan tousled. Lyft microdosing vice gatekeep literally pitchfork XOXO. Photo booth hot chicken yr, church-key gatekeep kogi shaman whatever. Locavore four loko irony, snackwave neutral milk hotel yes plz edison bulb poke food truck hot chicken. Live-edge blue bottle shoreditch slow-carb, dreamcatcher shaman pug grailed thundercats chartreuse beard bushwick.",

  "Hella dreamcatcher meditation cupping hoodie intelligentsia banjo tonx poke keytar neutral milk hotel bitters cold-pressed blackbird spyplane. Hella bicycle rights flexitarian thundercats next level, squid leggings. Adaptogen venmo kogi iceland, dreamcatcher fixie roof party snackwave artisan wolf. Sustainable tattooed direct trade intelligentsia raw denim",

  "Skateboard bushwick neutra pork belly, keffiyeh chicharrones gorpcore big mood tonx unicorn. Jianbing vegan put a bird on it mukbang taxidermy. Polaroid live-edge literally neutral milk hotel chillwave butcher subway tile. Selfies asymmetrical roof party disrupt sriracha. Austin yr actually four dollar toast shaman small batch before they sold out offal pug roof party asymmetrical. Direct trade mumblecore hexagon cronut blog yuccie affogato roof party air plant blue bottle whatever jean shorts succulents scenester iceland. Irony authentic cold-pressed hexagon.",

  "Kombucha pour-over tousled poke 8-bit. Sartorial gastropub retro stumptown helvetica. Banjo church-key raw denim hammock ramps. Selvage kickstarter vaporware lo-fi, farm-to-table distillery everyday carry helvetica. Salvia messenger bag man braid pickled actually biodiesel hexagon mlkshk microdosing af selfies health goth helvetica. Fashion axe salvia retro kitsch activated charcoal kinfolk pinterest etsy before they sold out trust fund tacos butcher marxism poutine drinking vinegar",
];
